version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: autohaus_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: autohaus
      MARIADB_USER: admin
      MARIADB_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: